<?php


namespace module\test\arrays;


use biz\helpers\base\ReplaceArrayValue;
use biz\helpers\base\UnsetArrayValue;
use CRequest;
use biz\helpers\ArrayHelper;

class TestArraysSortAction extends \CAction
{
    public function execute(CRequest $request)
    {
        $array1 = [
            'name' => 'Yii',
            'version' => '1.1',
            'ids' => [
                1,
            ],
            'validDomains' => [
                'example.com',
                'www.example.com',
            ],
            'emails' => [
                'admin' => 'admin@example.com',
                'dev' => 'dev@example.com',
            ],
        ];

        $array2 = [
            'version' => '2.0',
            'ids' => [
                2,
            ],
            'validDomains' => new ReplaceArrayValue([
                'yiiframework.com',
                'www.yiiframework.com',
            ]),
            'emails' => [
                'dev' => new UnsetArrayValue(),
            ],
        ];

        $result = ArrayHelper::merge($array1, $array2);

        var_dump($result);exit;


        return parent::execute($request); // TODO: Change the autogenerated stub
    }
}