<?php


namespace module\test\basic;


use CRequest;
use module\test\basic\server\MySayHelloWord;

class TestBasicTraitAction extends \CAction
{
    public function execute(CRequest $request)
    {

        $server = new MySayHelloWord();

        $server->sayHelloWord();

        exit;
        return parent::execute($request); // TODO: Change the autogenerated stub
    }
}