<?php


namespace module\test\basic;


use CRequest;

class TestBasicStringAction extends \CAction
{
    public function execute(CRequest $request)
    {
        //原始密码
        $pass = crypt('huangdingbofdfdas');

        //用户输入
        $sendPass = 'huangdingbofdfdas';

        if (hash_equals($pass, crypt($sendPass, $pass))) {
            echo "验证通过";
        }else{
            echo '验证不通过';
        }

        echo "<br>";

        var_dump($pass);exit;

        return parent::execute($request); // TODO: Change the autogenerated stub
    }
}