<?php


namespace module\test\join;


use biz\common\TestDataBaseConnectListenerInterface;
use CC\db\base\select\ListModel;
use CRequest;

class TestJoinIndexAction extends \CAction
{
    public function execute(CRequest $request)
    {
        $list = ListModel::make('websites')
            ->setDbConnectListener(new TestDataBaseConnectListenerInterface())
            ->leftJoin('access_log','a','t.id = a.site_id')
            ->execute();
        var_dump($list);exit;
        return parent::execute($request); // TODO: Change the autogenerated stub
    }
}