<?php
/**
 * Created by PhpStorm.
 * User: onwer
 * Date: 2018/1/8
 * Time: 12:03
 */

namespace module\core\login;


use CC;
use CC\action\module\core\login\CoreLoginIndexAdminAction;
use CC\util\common\server\SessionAbs;
use CErrorException;
use CRenderData;
use CRequest;
use Guzzle\Plugin\Cookie\Cookie;

class CoreLoginIndexWebAction extends CoreLoginIndexAdminAction
{
    public $validate;
    public function onCheck($data,&$mes){
        parent::onCheck($data,$mes);
        //判断session值与用户输入的验证码是否一致;
        session_start();

        if($this->validate != $_SESSION["authnum_session"] && CC\util\common\server\Cookie::get('core_login_account_remember') == ''){
            throw new CErrorException(CC::t('验证码错误'));
        }
    }
    protected function getViewDir()
    {
        return __DIR__;
    }

    protected function verifyPass($pass, $user_pass)
    {
        return parent::verifyPass($pass, $user_pass); // TODO: Change the autogenerated stub
    }
}