<?php


namespace module\test\ue;


use CRequest;
use module\test\ue\server\CommonServer;

class TestUeGetConditionByRoundAction extends \CAction
{
    public $center; //圆心
    public $radius; //半径

    public function execute(CRequest $request)
    {
        $list = CommonServer::requestApi('https://restapi.amap.com/v3/traffic/status/circle',[
           'location' => $this->center,
           'radius' => $this->radius,
            'key' => '3275d38f5e03c4c8a1451450207d54aa',
            'extensions' => 'all',
            'level' => '4',
        ]);

        if ($list['infocode'] != '10000'){
            throw new \CErrorException('获取数据失败');
        }

        return new \CJsonData(['list' => $list]); // TODO: Change the autogenerated stub
    }
}